### ISSUE TITLE
[Bug]: Camo infusment does not work stopping progression

### ISSUE THREAD

**Issue by schindlershadow** [Mrbysco/ForceCraft#102]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

neoforge 21.1.26

### Minecraft version

1.21.1

### Mod version

forcecraft-1.21.1-6.0.0

### Java version

openjdk version "21.0.4"

### Issue Description

Camo infusment does not work stopping progression at teir 3. the recipe is valid and infusing starts but the potion is not consumed and camo is not applied

The following infusments also do not work but do not stop progression:
bleeding
bane
lumberjack

### Additional Information

upgrade tome 
`<item:forcecraft:upgrade_tome>.withJsonComponent(<componenttype:forcecraft:upgrade_book>, {recipesUsed: ["forcecraft:infuser/infuse_bleeding", "forcecraft:infuser/infuse_pack_upgrade2", "forcecraft:infuser/infuse_silk"], progressCache: "3/4", tier: "3", points: 575})`

potion
`<item:minecraft:potion>.withJsonComponent(<componenttype:minecraft:potion_contents>, {potion: "minecraft:invisibility"})`

infusing
![image](https://github.com/user-attachments/assets/d3b77348-8d34-4da4-8dd9-aa8485aaede6)

no camo after infusing
![image](https://github.com/user-attachments/assets/ad5e2ee2-f2a7-4370-b1d6-c97b309fd640)

upgrade tome after infusing
`<item:forcecraft:upgrade_tome>.withJsonComponent(<componenttype:forcecraft:upgrade_book>, {recipesUsed: ["forcecraft:infuser/infuse_bleeding", "forcecraft:infuser/infuse_pack_upgrade2", "forcecraft:infuser/infuse_silk"], progressCache: "3/4", tier: "3", points: 575})`

**Comment by Raylo555** [comment]
marked as closed but the newest release still has this issue. 💀

**Comment by Mrbysco** [comment]
Are the other still an issue as well? Or was it just Camo that was still broken

**Comment by schindlershadow** [comment]
camo is now working and advances upgrade tome progression
![Screenshot from 2024-10-02 19-16-48](https://github.com/user-attachments/assets/d133047c-28db-4a80-a2bb-c5a55dec5a7b)


The following infusments still do not work:
bleeding - arrow is consumed but does not infuse item
bane - item is not consumed and does not infuse item
lumberjack - item is consumed, infuses item but does not break additional logs when breaking a log block

**Comment by Mrbysco** [comment]
Bane will work next update :) Found the issue

**Comment by Mrbysco** [comment]
Bleed was applying Bane for some reason

**Comment by Mrbysco** [comment]
Lumberjack has also been fixed
