### ISSUE TITLE
[Bug]: Patchouli Guide Book not showing up

### ISSUE THREAD

**Issue by Spontaneo** [Mrbysco/ForceCraft#103]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

Neoforge 21.1.61

### Minecraft version

1.21.1

### Mod version

6.0.0

### Java version

Java 11

### Issue Description

The "Force and You" guide book doesn't show in creative or JEI when trying to find it.  Using Patchouli version 1.21-87-Neoforge.

**Comment by Mrbysco** [comment]
Have you tried the recipe for a book + a force nugget?

**Comment by Spontaneo** [comment]
![2024-10-02 08_08_39-Minecraft NeoForge_ 1 21 1 - Singleplayer](https://github.com/user-attachments/assets/d68a5e1d-871e-4a0a-a833-75c0e52110d8)

Tried the book + force nugget and no result.  Attached is screen shot.

**Comment by Mrbysco** [comment]
I meant to say a book plus a force gem

**Comment by Spontaneo** [comment]
That worked!  Dunno why it isn't showing in any interface.
