### ISSUE TITLE
[Suggestion]: A Compendium section to Force and You.

### ISSUE THREAD

**Issue by Raylo555** [Mrbysco/ForceCraft#106]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

A list of of Objects that can be infused, with a comprehensive list for each item that can be added to them.
I.E. a Force Sword will have; A Claw for 1 damage, A Force Nugget for Knockback per level, A Fortune for Looting, etc. 

This would save the Player time instead of having to search through each level to see what goes on what.

**Comment by Mrbysco** [comment]
Each tier is locked behind advancements, having a page display all items will completely negate the tier locked pages
