### ISSUE TITLE
[Suggestion]: Remove Tag from Force Shears

### ISSUE THREAD

**Issue by TheBedrockMaster** [Mrbysco/ForceCraft#113]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

*This seems familiar*

Playing on 1.21.1 Neoforge and noticed that Force Shears have the `c:shears` item tag, which from what I can tell is only used on Force Shears.

**Comment by Mrbysco** [comment]
They should be in tools/shears unless I didn't re-run datagen

**Comment by Mrbysco** [comment]
Oh nvm, it's a leftover from before I started datagenning, will remove in a later build
