### ISSUE TITLE
Some Infusions Do Not Have a Tooltip

### ISSUE THREAD

**Issue by Darkosto** [Mrbysco/ForceCraft#18]
Infusions like Freezing on a bow do not appear in the tooltip making it difficult to know which items are infused:

![image](https://user-images.githubusercontent.com/10309699/120846609-3cd63600-c527-11eb-8c1d-1dce31962ac1.png)

**Comment by Mrbysco** [comment]
Next build they should all have tooltips. If not please re-open and specify the infusions that don't show in tooltip.
