### ISSUE TITLE
Add dimension whitelist/blacklist for world gen features

### ISSUE THREAD

**Issue by darkphan** [Mrbysco/ForceCraft#21]
### General Info

- [ ] I would like to propose new content
- [x] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

See title.

**Comment by TheDeviantCrafter** [comment]
As a temporary workaround for force ore, you could disable ore generation in the config then add it back using datapacks ore a mod like Large Ore Deposits. I'm not sure if the datapack method would work on trees.

**Comment by Mrbysco** [comment]
In 1.19 you'll be able to change where the ore generates by changing the biome modifiers through datapacks
