### ISSUE TITLE
recipe

### ISSUE THREAD

**Issue by sorimicro9** [Mrbysco/ForceCraft#23]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

recipe force stick please

**Comment by Mrbysco** [comment]
What do you mean? There's a recipe 
![image](https://user-images.githubusercontent.com/9308260/134506070-c8c7f51c-6b9d-4a9d-95e2-353de9786c2e.png)
