### ISSUE TITLE
[Bug]: bug with furnace 

### ISSUE THREAD

**Issue by RickyB505** [Mrbysco/ForceCraft#28]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

36.2.8

### Mod version

what ever the SkyFactory One pack has ver 1.01

### Java version

Java 14

### Issue Description

You can remove furnace upgrades by middle clicking them

https://user-images.githubusercontent.com/65817116/137433492-e1e55cd8-9ecd-4ac5-bf27-546b690d497b.mp4

**Comment by Mrbysco** [comment]
This bug exists due to Inventory Tweaks
