### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by MrReps** [Mrbysco/ForceCraft#33]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Hi
What does the heat core ? i couldn't find any information about it :/
thanks

**Comment by Mrbysco** [comment]
There's information about it in the book that you can find if you have Patchouli installed.
Where it mentions:

The **Heat Core** will increase the furnace efficiency by twofold, allowing you to smelt twice the amount of items/blocks with the same amount of fuel.

**Comment by MrReps** [comment]
Tanks for the info, i have already look in the book but didn't found the information. I looked in it again and finally found it. Maybe adding a link from the core upgrade to the furnace's core upgrade could be a good idea. Thanks
