### ISSUE TITLE
[Suggestion]: Bat Claws Should be Affected by Looting

### ISSUE THREAD

**Issue by Darkosto** [Mrbysco/ForceCraft#38]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

I just tested out killing bats with a Looting 3 infused Force Sword and it did not seem to affect the drop rates. Is this something we can add to help players out?

**Comment by Mrbysco** [comment]
I apparently made the claws reaaaaaaaally rare... as in where the claws had 1 weight but getting nothing had 15 weight meaning it'd rather choose nothing over something....
