### ISSUE TITLE
[Bug]: Using vanilla shears on a force tree leaves dropped force planks not force leaves.

### ISSUE THREAD

**Issue by AWDoBaun** [Mrbysco/ForceCraft#39]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

36.2.8

### Mod version

 forcecraft-1.16.5-1.0.7.1.jar

### Java version

1.8.0.51

### Issue Description

Using vanilla shears on a force tree leaves dropped force planks not force leaves.

**Comment by Mrbysco** [comment]
Fixed in upcoming 1.0.8

**Comment by Mrbysco** [comment]
https://github.com/Mrbysco/ForceCraft/commit/d04479360232c55f46c56dc5915f2bcea79e8102
