### ISSUE TITLE
[Suggestion]: Add a book entry to alert players on how to get Bat Claws

### ISSUE THREAD

**Issue by Darkosto** [Mrbysco/ForceCraft#40]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Currently, the mod does not give players information on how to get Bat Claws. It's a good idea to add this to the Patchouli book. 

Another suggestion may be to allow players to shear the claws from the bats. Bonus points if you can stop the bat from flying after it's been sheared.

**Comment by Mrbysco** [comment]
I've added an entry in 1.0.8.2.
I've added Shearing the bats into the Projects page of this github repo
