### ISSUE TITLE
[Suggestion]:  Please port to 1.18.1. 

### ISSUE THREAD

**Issue by b12arr0** [Mrbysco/ForceCraft#42]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Please consider porting to Minecraft 1.18.1.  This is such a great mod!  Thanks for resurrecting it.

**Comment by Mrbysco** [comment]
[Curseforge](https://www.curseforge.com/minecraft/mc-mods/forcecraft/files/3652183)
