### ISSUE TITLE
[Bug]: Client Crash While Launching

### ISSUE THREAD

**Issue by Darkfiend009** [Mrbysco/ForceCraft#43]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

39.0.79

### Mod version

2.0.0

### Java version

Java 17.0.1

### Issue Description

Client crash when initially trying to launch with Forge.

### Additional Information

https://pastebin.com/WABukgMn

**Comment by Mrbysco** [comment]
Could you try this maven build [Maven](https://maven.saps.dev/minecraft/com/mrbysco/forcecraft/forcecraft-1.18.1/2.0.1) (the top most build)

**Comment by Darkfiend009** [comment]
I just tried it myself since my tester isn't on currently. Still crashing when trying to start up.

https://pastebin.com/k4j77pW7

That was with the 2.0.1 Maven build.

**Comment by b12arr0** [comment]
I tried the 2.0.1 maven build as well. I started a new instance with forge 39.0.79 and only ForceCraft 1.18.1-2.0.1.  Same error as Darkfiend009.

**Comment by Mrbysco** [comment]
Working on it

**Comment by Mrbysco** [comment]
I've re-uploaded the 2.0.1 jar to the maven, the new one should be working, I was able to load with it

**Comment by b12arr0** [comment]
The 2.0.1 maven build is loading for me too.
