### ISSUE TITLE
[Bug]: Force Ore/Trees do not generate

### ISSUE THREAD

**Issue by OCDCleric** [Mrbysco/ForceCraft#60]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

41.1.0

### Mod version

1.19-3.0.0

### Java version

Java 8 Ver 333

### Issue Description

Force Trees and Force Ore do not generate in worlds. Not much else to say.

**Comment by Mrbysco** [comment]
Whoops, will be fixed next version
