### ISSUE TITLE
[Bug]: Force furnace auto-outputs smelted items upward, which messes with automation

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Mrbysco/ForceCraft#64]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

40.1.68

### Mod version

2.3.0

### Java version

Java 8 update 301

### Issue Description

I tried to put a hopper above the force furnace to automate it. After smelting some iron, the force furnace output the ingot into the hopper, which sent it back into furnace's input slot. 

Please remove the auto-output feature. It makes automation difficult.

**Comment by Mrbysco** [comment]
It outputs to the biggest inventory it can find which is intended behavior
