### ISSUE TITLE
[Bug]: Force Furcnace (Input item) (MP)

### ISSUE THREAD

**Issue by Mini-kun** [Mrbysco/ForceCraft#66]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.1.57

### Minecraft version

1.19.2

### Mod version

3.2.0

### Java version

17.0.5+9-LTS-191

### Issue Description

This only Effect the speed cord on the server
Does not Effect the Singleplayer at all

It Reset the Time for Smithing time back to 0.
If a new item is input into the Furnace

**Comment by Mrbysco** [comment]
I've been unable to reproduce this issue
