### ISSUE TITLE
no way to fill force wrench[Bug]: 

### ISSUE THREAD

**Issue by KaldurRahm** [Mrbysco/ForceCraft#67]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

latest

### Minecraft version

1.19

### Mod version

latest

### Java version

latest

### Issue Description

When you go to use the Force Wrench you can't use it. There is no hot key to open the Force Wrench's fuel tank. This is also missing for all Force tools.

Also when trying to craft the xp core no recipe works.

**Comment by Mrbysco** [comment]
Could you please provide more information about the version of the mod that you are using? Saying `Latest` here is incorrect as if you're playing a modpack then it's likely that they're a version behind.

Also please open an issue per problem
