### ISSUE TITLE
[Bug]: no GUI for force wrench and possibly other tools

### ISSUE THREAD

**Issue by reyrey2k8** [Mrbysco/ForceCraft#69]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

Forge 40.1.92

### Minecraft version

1.18.2

### Mod version

forcecraft-1.18.2-2.3.1.jar

### Java version

java 17.0.1 64bit /(CurseForge Default)

### Issue Description

Hi, I have been trying to figure out for the last 2-3 days on 2 different MC versions, with no luck, on how to open the force wrench so I can add force gems to transfer blocks similar to how DartCraft had its own wrench. When I try to shift+right click a block I get a message "insufficient force, needs 250 force to transport a block". I didn't see anything in the keybind options to open the wrench to add gems or anything in files that might indicate the option is available just not implemented yet. At least in the files, I was able to open and check, I don't have an MC eclipse dev environment. This is in my own custom Modpack with various mods that I normally try to play with. In my 1.19.2 pack, the wrench wouldn't open while being the only mod added, aside from Optifine and a keybind management mod(Controlling by Jaredlll08).

I've thought about trying to temporarily add its own GUI and function until it is implemented by digging through files and trying to study the code to see if I can make something up, but little knowledge of MC java code doesn't help on where to actually start. I've even tried SkyFactory One modpack to see if that had a "hack fix" implemented in some way, but no luck with that, as well as watching the Pack Dev playing with Forcecraft in his playthrough.

If you need any more info that might help, ill gladly provide what is needed. I'm stuck on what to do without racking my brain in code.

my main modpack(140 Mods)

MC 1.18.2
forcecraft-1.18.2-2.3.1.jar - the latest version from the Curseforge launcher
Forge 40.1.92

secondary mod pack

MC 1.19.2
forcecraft-1.19.2-3.2.0.jar - the latest version from the Curseforge launcher
Forge 43.2.0 - 2 versions behind from latest version atm(I typically wait a bit before I update forge)

**Comment by doritobob269** [comment]
I came here to report the exact same thing. I was even searching the source code for an answer, but I couldn't find any interaction to add force to the wrench. 
There is no keybind in the key handler file for opening a force wrench GUI. 
I see the code relating to picking up a block using force, but is adding force to the wrench itself still a feature being implemented/ported from a previous version?

**Comment by Mrbysco** [comment]
I was not aware there was such gui in DartCraft. In ForceCraft you were meant to infuse it in the Infuser but due to a bug that wasn't possible

**Comment by doritobob269** [comment]
> I was not aware there was such gui in DartCraft. In ForceCraft you were meant to infuse it in the Infuser but due to a bug that wasn't possible

The DartCraft GUI was very similar to the interface of the infuser where you input force gems and there was a fluid bar. It opened with Keybind F, but it might be pretty nice to have that in the infuser as you said.

**Comment by Mrbysco** [comment]
I had never played with Dartcraft before making this mod, so everything in Forcecraft is what I recreated from playtesting / checking wikis

**Comment by doritobob269** [comment]
> I had never played with Dartcraft before making this mod, so everything in Forcecraft is what I recreated from playtesting / checking wikis

Does the force wrench also pickup the block "Into" the force wrench or does it pick it up as a separate item? The reason I ask is would that mean I'd need a separate force wrench for every tile entity I want to pickup?
DartCraft used to pickup the block as a separate item. 
ie: If I shift-right click 4 chests with a wrench to pickup, I would have 4 slots in my inventory of chest items and 1 slot with the wrench still able to pickup other blocks.
