### ISSUE TITLE
[Bug]: Config changed message is at wrong log level

### ISSUE THREAD

**Issue by ChiefArug** [Mrbysco/ForceCraft#70]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

40.2.0

### Minecraft version

1.18.2

### Mod version

2.3.1

### Java version

java version 17.0.1 by Microsoft

### Issue Description

Why???
`[Thread-0/FATAL]: ForceCraft's config just got changed on the file system!`

https://github.com/Mrbysco/ForceCraft/blob/258706a804da6ba75714c991ba6f815b74354dea/src/main/java/com/mrbysco/forcecraft/config/ConfigHandler.java#L432

**Comment by Mrbysco** [comment]
Fixed in 1.19.2 (will backport in future)
