### ISSUE TITLE
[Suggestion]: Add config to disable need for RF for infuser

### ISSUE THREAD

**Issue by Goldenlion5648** [Mrbysco/ForceCraft#71]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

I am making a modpack that does not have any RF generators, and was wondering if it was possible to add a config to disable the need for RF for the infuser to run. I might be missing something, but ForceCraft on its own does not have a way of generating RF, meaning the infuser can not work without other mods installed.

**Comment by Mrbysco** [comment]
Forcecraft on is own has the Force Engine which generates RF
