### ISSUE TITLE
[Bug]: Time torch crashes server instantly

### ISSUE THREAD

**Issue by Kilazur** [Mrbysco/ForceCraft#74]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.2.3

### Minecraft version

1.19

### Mod version

3.2.2

### Java version

/

### Issue Description

Tried placing torches on a Resourceful furnace, server crashed. Looks like there is a recursion happening in the code leading to a StackOverflowException.

I can reproduce the same exact crash in single player with no other mods.

It seems the problem happens when two torches are next to one another.

### Additional Information

​​‍‍​​​‍​​‍‍​‍‍​​​‍‍​‍‍‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍‍​​‍​​‍‍​​‍​​​‍‍‍​​‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍​​​​​​‍‍​​​​​​‍‍​​​​05.02 11:29:15 [Server] at com.mrbysco.forcecraft.blockentities.TimeTorchBlockEntity.tickBlock(TimeTorchBlockEntity.java:77) ~[forcecraft-1.19.2-3.2.2.jar%23471!/:3.2.{re:classloading}
​​‍‍​​​‍​​‍‍​‍‍​​​‍‍​‍‍‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍‍​​‍​​‍‍​​‍​​​‍‍‍​​‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍​​​​​​‍‍​​​​​​‍‍​​​​05.02 11:29:15 [Server] at com.mrbysco.forcecraft.blockentities.TimeTorchBlockEntity.tickNeighbor(TimeTorchBlockEntity.java:58) ~[forcecraft-1.19.2-3.2.2.jar%23471!/:3.2.{re:classloading}
​​‍‍​​​‍​​‍‍​‍‍​​​‍‍​‍‍‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍‍​​‍​​‍‍​​‍​​​‍‍‍​​‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍​​​​​​‍‍​​​​​​‍‍​​​​05.02 11:29:15 [Server] at com.mrbysco.forcecraft.blockentities.TimeTorchBlockEntity.serverTick(TimeTorchBlockEntity.java:46) ~[forcecraft-1.19.2-3.2.2.jar%23471!/:3.2.{re:classloading}
[12:29 PM] 
BOT
 Bisect Panel Bot: ​​‍‍​​​‍​​‍‍​‍‍​​​‍‍​‍‍‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍‍​​‍​​‍‍​​‍​​​‍‍‍​​‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍​​​​​​‍‍​​​​​​‍‍​​​​05.02 11:29:15 [Server] at com.mrbysco.forcecraft.blockentities.TimeTorchBlockEntity.tickBlock(TimeTorchBlockEntity.java:99) ~[forcecraft-1.19.2-3.2.2.jar%23471!/:3.2.{re:classloading}
​​‍‍​​​‍​​‍‍​‍‍​​​‍‍​‍‍‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍‍​​‍​​‍‍​​‍​​​‍‍‍​​‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍​​​​​​‍‍​​​​​​‍‍​​​​05.02 11:29:15 [Server] at com.mrbysco.forcecraft.blockentities.TimeTorchBlockEntity.tickNeighbor(TimeTorchBlockEntity.java:58) ~[forcecraft-1.19.2-3.2.2.jar%23471!/:3.2.{re:classloading}
​​‍‍​​​‍​​‍‍​‍‍​​​‍‍​‍‍‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍‍​​‍​​‍‍​​‍​​​‍‍‍​​‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍​​​​​​‍‍​​​​​​‍‍​​​​05.02 11:29:15 [Server] at com.mrbysco.forcecraft.blockentities.TimeTorchBlockEntity.serverTick(TimeTorchBlockEntity.java:46) ~[forcecraft-1.19.2-3.2.2.jar%23471!/:3.2.{re:classloading}
​​‍‍​​​‍​​‍‍​‍‍​​​‍‍​‍‍‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍‍​​‍​​‍‍​​‍​​​‍‍‍​​‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍​​​​​​‍‍​​​​​​‍‍​​​​05.02 11:29:15 [Server] at com.mrbysco.forcecraft.blockentities.TimeTorchBlockEntity.tickBlock(TimeTorchBlockEntity.java:99) ~[forcecraft-1.19.2-3.2.2.jar%23471!/:3.2.{re:classloading}
​​‍‍​​​‍​​‍‍​‍‍​​​‍‍​‍‍‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍‍​​‍​​‍‍​​‍​​​‍‍‍​​‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍​​​​​​‍‍​​​​​​‍‍​​​​05.02 11:29:15 [Server] at com.mrbysco.forcecraft.blockentities.TimeTorchBlockEntity.tickNeighbor(TimeTorchBlockEntity.java:58) ~[forcecraft-1.19.2-3.2.2.jar%23471!/:3.2.{re:classloading}
​​‍‍​​​‍​​‍‍​‍‍​​​‍‍​‍‍‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍‍​​‍​​‍‍​​‍​​​‍‍‍​​‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍​​​​​​‍‍​​​​​​‍‍​​​​05.02 11:29:15 [Server] at com.mrbysco.forcecraft.blockentities.TimeTorchBlockEntity.serverTick(TimeTorchBlockEntity.java:46) ~[forcecraft-1.19.2-3.2.2.jar%23471!/:3.2.{re:classloading}
[12:29 PM] 
BOT
 Bisect Panel Bot: ​​‍‍​​​‍​​‍‍​‍‍​​​‍‍​‍‍‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍‍​​‍​​‍‍​​‍​​​‍‍‍​​‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍​​​​​​‍‍​​​​​​‍‍​​​​05.02 11:29:15 [Server] at com.mrbysco.forcecraft.blockentities.TimeTorchBlockEntity.tickBlock(TimeTorchBlockEntity.java:99) ~[forcecraft-1.19.2-3.2.2.jar%23471!/:3.2.{re:classloading}
​​‍‍​​​‍​​‍‍​‍‍​​​‍‍​‍‍‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍‍​​‍​​‍‍​​‍​​​‍‍‍​​‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍​​​​​​‍‍​​​​​​‍‍​​​​05.02 11:29:15 [Server] at com.mrbysco.forcecraft.blockentities.TimeTorchBlockEntity.tickNeighbor(TimeTorchBlockEntity.java:58) ~[forcecraft-1.19.2-3.2.2.jar%23471!/:3.2.{re:classloading}
​​‍‍​​​‍​​‍‍​‍‍​​​‍‍​‍‍‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍‍​​‍​​‍‍​​‍​​​‍‍‍​​‍​​‍‍​‍​‍​​‍‍​‍​‍​​‍‍​​​​​​‍‍​​​​​​‍‍​​​​05.02 11:29:15 [Server] at com.mrbysco.forcecraft.blockentities.TimeTorchBlockEntity.serverTick(TimeTorchBlockEntity.java:46) ~[forcecraft-1.19.2-3.2.2.jar%23471!/:3.2.{re:classloading}

**Comment by Mrbysco** [comment]
Could you upload the actual crashlog to a website like Pastebin? or upload the log into this issue

**Comment by Kilazur** [comment]
https://pastebin.com/PQ5HpuL8

**Comment by Mrbysco** [comment]
Could you try the latest build on curseforge?

**Comment by Kilazur** [comment]
Crash is gone, but the torches don't seem to do anything. Gonna go back to the associated ticket.
