### ISSUE TITLE
[Suggestion]: Config to decrease Force Tree spawn rate.

### ISSUE THREAD

**Issue by Verbina29** [Mrbysco/ForceCraft#77]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

They seem too common, so it'd be nice if the rate were configurable.

**Comment by Mrbysco** [comment]
In 1.19+ the rarity can be changed using a datapack

**Comment by Verbina29** [comment]
Ah, how do you do that?

**Comment by Mrbysco** [comment]
Have a look at this document written by Darkosto https://moddertools.darkosto.com/datapacks

**Comment by Verbina29** [comment]
I meant "How do I make Force Trees less common with a datapack", not "How do I make a datapack".

**Comment by Mrbysco** [comment]
Oh, I'm used to being asked 'how do I create a datapack'...
You can change the rarity by adjusting the rarity value found in `data/forcecraft/worldgen/placed_feature/force_tree.json'
https://github.com/Mrbysco/ForceCraft/blob/1.19.x/src/generated/resources/data/forcecraft/worldgen/placed_feature/force_tree.json#L4-L7

**Comment by Mrbysco** [comment]
If you put a changed version of that file in your datapack under the same folder structure it'll reduce/increase the rarity based on what you've set it to :)
