### ISSUE TITLE
[Bug]: Force wrench voids container

### ISSUE THREAD

**Issue by Saereth** [Mrbysco/ForceCraft#78]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.2.14

### Minecraft version

1.19.2

### Mod version

forcecraft-1.19.2-3.2.7

### Java version

17.0.2+8

### Issue Description

Wrenching an iron chest filled with items voids the chest contents. 
Original issue reported here for ftb skies:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2978

**Comment by Mrbysco** [comment]
Whoops
