### ISSUE TITLE
[Bug]: Power ore doesn't generate?

### ISSUE THREAD

**Issue by AlexiyOrlov** [Mrbysco/ForceCraft#80]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.1.3

### Minecraft version

1.20.1

### Mod version

4.1.0

### Java version

17

### Issue Description

I can't find power ore, it doesn't generate anywhere

**Comment by Mrbysco** [comment]
A new version is being uploaded to curseforge (4.1.1) that should fix the issue
