### ISSUE TITLE
[Bug]: Time Torch loop with BotanyPods causes server crash

### ISSUE THREAD

**Issue by Kehaan** [Mrbysco/ForceCraft#83]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

36.2.39

### Minecraft version

1.16.5

### Mod version

1.16.5-1.0.8.4

### Java version

1.8.0_312

### Issue Description

I am the creator of "Pokehaan Craft 2" A user reported a server crash using time torches and BotanyPods by Darkhax. Darkhax forwarded me to here. But he may contact you too. Seems like the user enabled the time torches, as those are not enabled by default... But maybe others have the same issue with Time Torches and BotanyPods as that user do.

https://legacy.curseforge.com/minecraft/modpacks/pokehaan-craft-2/issues/35

### Additional Information

Crashlog: https://pastebin.com/qEw21ynf

**Comment by Mrbysco** [comment]
I've backported some of the fixes/changes I've done in newer versions back to 1.16.5 and a new version is being uploaded to curse. It includes some fixes I've done to the time torch recently

**Comment by Mrbysco** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/forcecraft/files/4872848

**Comment by Kehaan** [comment]
Thank you very much
