### ISSUE TITLE
[Bug]: Crash when updating to newest Forcraft

### ISSUE THREAD

**Issue by Kehaan** [Mrbysco/ForceCraft#84]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

36.2.39

### Minecraft version

1.16.5

### Mod version

1.16.5-1.2.0

### Java version

1.8.0_51

### Issue Description

Hello

Back again, just tryed the new update to the 1.16.5 version to fix the Time Torch. However, once i load up the modpack it seems i crash. It does not create a crashlog, but the "latest" log can be found below.

Only thing i changed was updating the mod in the pack.

### Additional Information

https://pastebin.com/e40fKubY

**Comment by Mrbysco** [comment]
I didn't even touch the mixins.... Let's try building again

**Comment by Mrbysco** [comment]
Could you test 1.2.1

**Comment by Kehaan** [comment]
I can load the pack now with 1.2.1 :)

Side note, if i disable the "Time Torch" i can still see it in JEI, i take that is intended? (It does not seem to be craftable) This was also the case in 1.0.8.4. So i take the disabling of the time torch did not change between the 2 versions? (Just double checking) as right now the public pack just uses the old version of the mod, with the time torch disabled (I had a corrupted config that i fixed, lol)

The crash is now fixed :) Just not sure waht the backport from the 1.16.5 besides the crash was fixed <3 (As it also mentions a config, so just double checking the "Old" version. Still disable it fine, ahha)

**Comment by Mrbysco** [comment]
It's intentional, I am not a fan of hiding content from JEI :P 
![image](https://github.com/Mrbysco/ForceCraft/assets/9308260/0a5c1b20-727e-4ac2-a83f-e52f6cf0c294)
It's basically stuff I've fixed over the years but hadn't backported yet as I had no reason to

**Comment by Kehaan** [comment]
Ah, i was just wondering what the "config option / fixes" included :P But it seemed like in 1.0.8.4 it did disable it. So i guess other config issues xD Thanks for the quick help. Will update the pack with the new version in a week-ish :)
