### ISSUE TITLE
[Client crash] Unexpected error - caused by Watcher (alexcaves)

### ISSUE THREAD

**Issue by DevDyna** [Mrbysco/ForceCraft#85]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.2.4

### Minecraft version

1.20.1

### Mod version

forcecraft-1.20.1-4.1.4

### Java version

17.0.8

### Issue Description

[from alexcaves repo](https://github.com/AlexModGuy/AlexsCaves/issues/652)
> After summoned it send on crash [idk if was caused mainly by AlexCaves or Forcecraft]

verified and keep on crashing on 4.1.4 at same way

### Additional Information

modlist that i have used on latest version
[Exploration Fabrique-2.1.zip](https://github.com/Mrbysco/ForceCraft/files/13473391/Exploration.Fabrique-2.1.zip)
[crash-2023-11-27_12.06.51-client.txt](https://github.com/Mrbysco/ForceCraft/files/13473432/crash-2023-11-27_12.06.51-client.txt)

**Comment by Mrbysco** [comment]
Fixed next release
