### ISSUE TITLE
[Bug]: Incompatibility with Mahou Tsukai's Mental Displacement

### ISSUE THREAD

**Issue by robertmaxton42** [Mrbysco/ForceCraft#86]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.3.0

### Minecraft version

1.19.2

### Mod version

3.3.2

### Java version

OpenJDK 17

### Issue Description

When using Mental Displacement in a modpack with ForceCraft also installed, the client immediately crashes with the error

```
java.lang.ClassCastException: class stepsword.mahoutsukai.entity.MentalDisplacementEntity cannot be cast to class net.minecraft.world.entity.player.Player
```

The Mahoutsukai dev tells me that it's apparently on ForceCraft's end and there's nothing he can do about it, so I'm making the issue here. The crash report is attached.

### Additional Information

https://pastebin.com/m2GTzSvU

**Comment by Mrbysco** [comment]
I fixed this issue in 1.20, will backport later today

**Comment by impossiblearchitect** [comment]
That was nice and fast. Thanks!

**Comment by robertmaxton42** [comment]
That was nice and fast. Thanks!
