### ISSUE TITLE
[Bug]: Time Torch Crash

### ISSUE THREAD

**Issue by DinnerBeef** [Mrbysco/ForceCraft#87]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.3.5

### Minecraft version

1.19.2

### Mod version

3.3.3

### Java version

17.0.3.1

### Issue Description

Placing down Two time torches at least on a wall seems to crash randomly. So far, I have only seen it happen with thermal machines, not sure if it happens with anything else.  

Note: This issue was first found on a server then tested more in SP 

See Video Below!

### Additional Information

https://s.dinnerbeef.com/gOXe5/VuzIkiGO17.mp4/raw
https://s.dinnerbeef.com/gOXe5/yiNUHAja20.txt

**Comment by Mrbysco** [comment]
🤦 is the one time torch ticking the other time torch and thus creating a loop?

**Comment by DinnerBeef** [comment]
That was my first thought. But it was a bit random when I was making the video. So 🤷

**Comment by Mrbysco** [comment]
It's because I wasn't checking for the wall variant

**Comment by Mrbysco** [comment]
Will be building and publishing new versions for 1.19 and 1.20 :)

**Comment by Mrbysco** [comment]
The jars have been uploaded and are under review. In the mean time they're available on Modrinth already
