### ISSUE TITLE
Crash on custom modpack

### ISSUE THREAD

**Issue by Majestyc2k1** [Mrbysco/ForceCraft#88]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

Neoforge 20.4.232

### Minecraft version

1.20.4

### Mod version

1.20.4-5.0.0

### Java version

Java 8 update 333

### Issue Description

When smelting in the Force furnace, the game crashed when the smelted item tried going into the output slot. First happened on clay, I also tried copper.

### Additional Information

https://pastebin.com/qgMpxMG4

**Comment by Mrbysco** [comment]
A new build is being created

**Comment by Mrbysco** [comment]
A new build has been uploaded to Curseforge and Modrinth. It should be available on curseforge soon

**Comment by Majestyc2k1** [comment]
Appears to be working now. Thank you.
