### ISSUE TITLE
[Question]: Version 4.1.8+ still beta curseforge?

### ISSUE THREAD

**Issue by IONayrus** [Mrbysco/ForceCraft#97]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

On the curseforge website, version 4.1.7 from feb is still set as the main release which sucks cause 4.1.8 from march implemented automation. So is there still a need for the newer version to be in beta?

**Comment by Mrbysco** [comment]
Probably forgot to change the type that is set to new versions, I marked 4.2.0 as a release
