### ISSUE TITLE
[Bug]: Error saving [1 forcecraft:experience_tome]. Original cause: java.lang.IllegalStateException: Value must be positive: 0

### ISSUE THREAD

**Issue by schindlershadow** [Mrbysco/ForceCraft#98]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

neoforge 21.1.26

### Minecraft version

1.21.1

### Mod version

forcecraft-1.21.1-6.0.0

### Java version

openjdk version "21.0.4"

### Issue Description

Using experience tome causes server error and client crash

### Additional Information

Client crash report: https://pastebin.com/raw/c0sUyfBX

Log from server:
```
[04Sep2024 21:04:39.465] [Server thread/ERROR] [net.minecraft.Util/]: Error saving [1 forcecraft:experience_tome]. Original cause: java.lang.IllegalStateException: Value must be positive: 0
With components:
{
	forcecraft:tome_experience=>0
	minecraft:max_stack_size=>1
	minecraft:lore=>ItemLore[lines=[], styledLines=[]]
	minecraft:enchantments=>ItemEnchantments{enchantments={}, showInTooltip=true}
	minecraft:repair_cost=>0
	minecraft:attribute_modifiers=>ItemAttributeModifiers[modifiers=[], showInTooltip=true]
	minecraft:rarity=>COMMON
}
With tag: {Slot:7b}
[04Sep2024 21:04:39.525] [Server thread/WARN] [net.minecraft.world.level.storage.PlayerDataStorage/]: Failed to save player data for SchindlerShadow
```

**Comment by Mrbysco** [comment]
Will look into it
